[package]
name = "feenk-signer"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "feenk-signer"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1", features = [ "derive", "env" ] }
execute = "0.2"
rand = "0.8"
ndk-build = "0.9"